language: go
go:
  - 1.11.x

before_install:
  # Initialize Go module (if not already done)
  - go mod init your-module-name || echo "Go module already initialized."

install:
  # Install Hugo (assuming you have go.mod now)
  - go get github.com/gohugoio/hugo

script:
  # Create the theme directory and clone the beautifulhugo theme
  - mkdir -p themes/beautifulhugo && git clone https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
  # Run Hugo with the specified theme
  - hugo --theme=beautifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
