language: go
go:
  - 1.21.x

install:
  - go install github.com/gohugoio/hugo@latest

script:
  - mkdir -p themes/beautifulhugo && git clone https://GitHub.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: \$GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
    env:
  global:
    - GITHUB_TOKEN=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
